version: '3'
services:
  db:
    restart: always
    image: "postgres:11.8-alpine"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
